version: "2"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/Desktop/prueba-rest-api/data:/data/db
    networks:
      - mongo-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    networks:
      - mongo-network

networks:
    mongo-network:
      driver: bridge
